# .eslintrc.yaml
---
  extends: airbnb-base
  rules:
    import/no-unresolved: 2,
    import/extensions: 2,
    caseSensitive: false
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  settings:
    import/extensions: off
    import/no-unresolved: off
